name: test-go-run

on:
  pull_request:
    branches:
      - develop

permissions:
  contents: write
  packages: read
  pull-requests: write

jobs:
  go-run:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.git-diff.outputs.changes }}
    steps:
      - uses: actions/checkout@v3

      - name: go setup
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: go run
        run: |
          export GITHUB_TOKEN=${{ secrets.TAIKI_TOKEN }}
          go run main.go
      
      - name: Check for changes
        id: git-diff
        run: |
          git diff --quiet || echo "::set-output name=changes::true"

      - name: commit-push
        if: steps.git-diff.outputs.changes == 'true'
        run: |
          echo "check for changes true"
