name: test-go-run

on:
  pull_request:
    branches:
      - develop

permissions:
  contents: write
  packages: read
  pull-requests: write

jobs:
  build-and-format:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.diff.outputs.changes }}
      count: ${{ steps.check-pr.outputs.count }}
    steps:
      - uses: actions/checkout@v3

      - name: go setup
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: go run
        run: |
          export GITHUB_TOKEN=${{ secrets.TAIKI_TOKEN }}
          go run main.go

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Format JSON files
        run: |
          npm install --save-dev prettier
          npx prettier --write '**/*.json'

      - name: Check for changes
        id: diff
        run: |
          if git diff --quiet; then
            echo "changes=none" >> "$GITHUB_OUTPUT"
          else
            echo "changes=found" >> "$GITHUB_OUTPUT"
          fi

      - name: commit-push
        if: ${{ steps.diff.outputs.changes == 'found' }}
        run: |
          echo "commit-push"
      
      - name: check pr
        id: check-pr
        run: |
          echo "count=$(gh pr list --state open --base main | wc -l)" >> "$GITHUB_OUTPUT"

  create-pull-request:
    runs-on: ubuntu-latest
    needs: build-and-format
    if: ${{ needs.build-and-format.outputs.count == 0 }} and ${{ needs.build-and-format.outputs.changes == 'found' }}
    env:
      GH_TOKEN: ${{ secrets.TAIKI_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: create release pr      
        run: |
          echo "create release pr"